const profiles = [
    {
        id: 1,
        name: "Ayesha Khan",
        age: 26,
        location: "Mumbai",
        profession: "Software Engineer",
        image: "https://randomuser.me/api/portraits/women/1.jpg",
    },
    {
        id: 2,
        name: "Rohit Sharma",
        age: 30,
        location: "Delhi",
        profession: "Doctor",
        image: "https://randomuser.me/api/portraits/men/2.jpg",
    },
    {
        id: 3,
        name: "Priya Verma",
        age: 25,
        location: "Bangalore",
        profession: "Data Analyst",
        image: "https://randomuser.me/api/portraits/women/3.jpg",
    },
    {
        id: 4,
        name: "Aman Joshi",
        age: 28,
        location: "Pune",
        profession: "UX Designer",
        image: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    {
        id: 5,
        name: "Neha Desai",
        age: 27,
        location: "Ahmedabad",
        profession: "Marketing Manager",
        image: "https://randomuser.me/api/portraits/women/5.jpg",
    },
    {
        id: 6,
        name: "Karan Mehta",
        age: 31,
        location: "Chandigarh",
        profession: "Chartered Accountant",
        image: "https://randomuser.me/api/portraits/men/6.jpg",
    },
    {
        id: 7,
        name: "Sneha Reddy",
        age: 24,
        location: "Hyderabad",
        profession: "Architect",
        image: "https://randomuser.me/api/portraits/women/7.jpg",
    },
    {
        id: 8,
        name: "Nikhil Kumar",
        age: 29,
        location: "Kolkata",
        profession: "Business Analyst",
        image: "https://randomuser.me/api/portraits/men/8.jpg",
    },
    {
        id: 9,
        name: "Pooja Sharma",
        age: 26,
        location: "Noida",
        profession: "Graphic Designer",
        image: "https://randomuser.me/api/portraits/women/9.jpg",
    },
    {
        id: 10,
        name: "Arjun Singh",
        age: 32,
        location: "Jaipur",
        profession: "Civil Engineer",
        image: "https://randomuser.me/api/portraits/men/10.jpg",
    },
    {
        id: 11,
        name: "Meera Nair",
        age: 29,
        location: "Kochi",
        profession: "HR Manager",
        image: "https://randomuser.me/api/portraits/women/11.jpg",
    },
    {
        id: 12,
        name: "Vikram Patel",
        age: 27,
        location: "Surat",
        profession: "Banker",
        image: "https://randomuser.me/api/portraits/men/12.jpg",
    },
    {
        id: 13,
        name: "Riya Das",
        age: 25,
        location: "Bhubaneswar",
        profession: "Content Writer",
        image: "https://randomuser.me/api/portraits/women/13.jpg",
    },
    {
        id: 14,
        name: "Deepak Yadav",
        age: 28,
        location: "Lucknow",
        profession: "Lawyer",
        image: "https://randomuser.me/api/portraits/men/14.jpg",
    },
    {
        id: 15,
        name: "Tanya Kapoor",
        age: 30,
        location: "Gurgaon",
        profession: "Teacher",
        image: "https://randomuser.me/api/portraits/women/15.jpg",
    },
    {
        id: 16,
        name: "Siddharth Roy",
        age: 26,
        location: "Nagpur",
        profession: "Mechanical Engineer",
        image: "https://randomuser.me/api/portraits/men/16.jpg",
    },
    {
        id: 17,
        name: "Isha Singh",
        age: 27,
        location: "Indore",
        profession: "Pharmacist",
        image: "https://randomuser.me/api/portraits/women/17.jpg",
    },
    {
        id: 18,
        name: "Raj Malhotra",
        age: 29,
        location: "Amritsar",
        profession: "IT Consultant",
        image: "https://randomuser.me/api/portraits/men/18.jpg",
    },
    {
        id: 19,
        name: "Divya Bhatt",
        age: 24,
        location: "Raipur",
        profession: "Social Media Manager",
        image: "https://randomuser.me/api/portraits/women/19.jpg",
    },
    {
        id: 20,
        name: "Harsh Vardhan",
        age: 31,
        location: "Bhopal",
        profession: "Entrepreneur",
        image: "https://randomuser.me/api/portraits/men/20.jpg",
    },
];

export default profiles;
